name: Setup LLVM & Clang environment
description: 🚀 Installs LLVM/Clang and friends

inputs:
  llvm-version:
    default: latest
  set-bin:
    default: false
  set-env:
    default: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export DENO_INSTALL="$GITHUB_ACTION_PATH/.deno"
        export DENO_VERSION=1.37.0
        curl -fsSL https://deno.land/install.sh | sh -s "v$DENO_VERSION"
    - shell: bash
      run: |
        "$GITHUB_ACTION_PATH/.deno/bin/deno" \
          run -Aq "$GITHUB_ACTION_PATH/main.sh"
      env:
        INPUT_LLVM_VERSION: ${{ inputs.llvm-version }}
        INPUT_SET_BIN: ${{ inputs.set-bin }}
        INPUT_SET_ENV: ${{ inputs.set-env }}
