name: Setup LLVM & Clang toolchain
description: 🚀 Installs LLVM/Clang and friends for GitHub Actions

inputs:
  llvm-toolchain-version:
    default: latest
  set-env:
    default: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export DENO_INSTALL="$GITHUB_ACTION_PATH/.deno"
        export DENO_VERSION=1.37.0
        curl -fsSL https://deno.land/install.sh | sh -s "v$DENO_VERSION"
    - shell: bash
      run: |
        "$GITHUB_ACTION_PATH/.deno/bin/deno" \
          run -Aq "$GITHUB_ACTION_PATH/main.ts"
      env:
        INPUT_LLVM-TOOLCHAIN-VERSION: ${{ inputs.llvm-toolchain-version }}
        INPUT_SET-ENV: ${{ inputs.set-env }}
